// Generated by https://quicktype.io

export interface Hero {
  superhero:        string;
  publisher:        string;
  alter_ego:        string;
  first_appearance: string;
  characters:       string;
}
